{{- if .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "summit-common-helm_chart-svc.fullname" . }}
  labels:
    {{- include "summit-common-helm_chart-svc.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
...
{{- end }}
