---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "summit-common-helm_chart-svc.fullname" .) .Values.service.name }}
  labels:
    {{- include "summit-common-helm_chart-svc.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- include "summit-common-helm_chart-svc.tplValue" (dict "value" .Values.service.loadBalancerSourceRanges "context" $) | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "summit-common-helm_chart-svc.selectorLabels" . | nindent 4 }}
...